export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  popular: boolean;
  allergens: string;
  variants: {
    id: string;
    name: string;
    price: number;
  }[];
}

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: 'mock-kabuli-pilau',
    name: 'Kabuli Pilau (Lamb Shank)',
    slug: 'kabuli-pilau-lamb-shank',
    description: 'Traditional Afghan rice with raisins, carrots & tender lamb shank.',
    category: 'Afghan Specials',
    popular: true,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-kabuli-standard', name: 'Standard', price: 1499 },
    ],
  },
  {
    id: 'mock-chicken-biryani',
    name: 'Chicken Biryani',
    slug: 'chicken-biryani',
    description: 'Fragrant spiced rice with chicken & raita.',
    category: 'Afghan Specials',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-chicken-biryani-standard', name: 'Standard', price: 999 },
    ],
  },
  {
    id: 'mock-lamb-biryani',
    name: 'Lamb Biryani',
    slug: 'lamb-biryani',
    description: 'Spiced lamb with saffron rice & salad.',
    category: 'Afghan Specials',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-lamb-biryani-standard', name: 'Standard', price: 1099 },
    ],
  },
  {
    id: 'mock-mantu',
    name: 'Mantu',
    slug: 'mantu',
    description: 'Steamed dumplings filled with minced beef, topped with tomato & yoghurt sauce.',
    category: 'Afghan Specials',
    popular: true,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-mantu-standard', name: 'Standard', price: 899 },
    ],
  },
  {
    id: 'mock-bolani',
    name: 'Bolani',
    slug: 'bolani',
    description: 'Crispy flatbread stuffed with potato & herbs.',
    category: 'Afghan Specials',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-bolani-standard', name: 'Standard', price: 699 },
    ],
  },
  {
    id: 'mock-lamb-karahi',
    name: 'Lamb Karahi',
    slug: 'lamb-karahi',
    description: 'Tomato, ginger & green chilli base — classic Afghan karahi.',
    category: 'Karahi',
    popular: true,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-lamb-karahi-standard', name: 'Standard', price: 1299 },
    ],
  },
  {
    id: 'mock-chicken-karahi',
    name: 'Chicken Karahi',
    slug: 'chicken-karahi',
    description: 'Mild or spicy option, cooked in authentic Afghan masala.',
    category: 'Karahi',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-chicken-karahi-mild', name: 'Mild', price: 1199 },
      { id: 'mock-chicken-karahi-spicy', name: 'Spicy', price: 1199 },
    ],
  },
  {
    id: 'mock-paneer-karahi',
    name: 'Paneer Karahi',
    slug: 'paneer-karahi',
    description: 'Cottage cheese in spicy tomato & capsicum gravy.',
    category: 'Karahi',
    popular: false,
    allergens: 'Dairy',
    variants: [
      { id: 'mock-paneer-karahi-standard', name: 'Standard', price: 1099 },
    ],
  },
  {
    id: 'mock-mix-karahi',
    name: 'Mix Karahi (Lamb + Chicken)',
    slug: 'mix-karahi',
    description: 'Double meat combo for sharing.',
    category: 'Karahi',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-mix-karahi-standard', name: 'Standard', price: 1399 },
    ],
  },
  {
    id: 'mock-vegetable-karahi',
    name: 'Vegetable Karahi',
    slug: 'vegetable-karahi',
    description: 'Seasonal veggies in tomato gravy.',
    category: 'Karahi',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-vegetable-karahi-standard', name: 'Standard', price: 949 },
    ],
  },
  {
    id: 'mock-chicken-doner',
    name: 'Chicken Doner',
    slug: 'chicken-doner',
    description: 'Marinated slices with salad & sauce.',
    category: 'Doner & Grill',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-chicken-doner-standard', name: 'Standard', price: 899 },
    ],
  },
  {
    id: 'mock-lamb-doner',
    name: 'Lamb Doner',
    slug: 'lamb-doner',
    description: 'Juicy lamb doner with salad & garlic sauce.',
    category: 'Doner & Grill',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-lamb-doner-standard', name: 'Standard', price: 949 },
    ],
  },
  {
    id: 'mock-mixed-doner',
    name: 'Mixed Doner',
    slug: 'mixed-doner',
    description: 'Half chicken, half lamb, served on naan.',
    category: 'Doner & Grill',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-mixed-doner-standard', name: 'Standard', price: 1049 },
    ],
  },
  {
    id: 'mock-chicken-tikka',
    name: 'Chicken Tikka',
    slug: 'chicken-tikka',
    description: 'Grilled chunks marinated overnight.',
    category: 'Doner & Grill',
    popular: true,
    allergens: 'Dairy',
    variants: [
      { id: 'mock-chicken-tikka-standard', name: 'Standard', price: 999 },
    ],
  },
  {
    id: 'mock-lamb-chops',
    name: 'Lamb Chops (4pcs)',
    slug: 'lamb-chops',
    description: 'Charcoal grilled, with mint sauce.',
    category: 'Doner & Grill',
    popular: false,
    allergens: 'Dairy',
    variants: [
      { id: 'mock-lamb-chops-standard', name: 'Standard', price: 1249 },
    ],
  },
  {
    id: 'mock-seekh-kebab',
    name: 'Seekh Kebab (2pcs)',
    slug: 'seekh-kebab',
    description: 'Spiced minced lamb skewers.',
    category: 'Doner & Grill',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-seekh-kebab-standard', name: 'Standard', price: 849 },
    ],
  },
  {
    id: 'mock-margherita-pizza',
    name: 'Margherita',
    slug: 'margherita',
    description: 'Classic tomato and mozzarella.',
    category: 'Pizza',
    popular: true,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-margherita-10', name: '10"', price: 999 },
      { id: 'mock-margherita-12', name: '12"', price: 1199 },
    ],
  },
  {
    id: 'mock-chicken-tikka-pizza',
    name: 'Chicken Tikka Pizza',
    slug: 'chicken-tikka-pizza',
    description: 'Spiced chicken tikka on pizza base.',
    category: 'Pizza',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-ctp-10', name: '10"', price: 1099 },
      { id: 'mock-ctp-12', name: '12"', price: 1299 },
    ],
  },
  {
    id: 'mock-pepperoni-pizza',
    name: 'Pepperoni Pizza',
    slug: 'pepperoni-pizza',
    description: 'Classic pepperoni with mozzarella.',
    category: 'Pizza',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-pepperoni-10', name: '10"', price: 1099 },
      { id: 'mock-pepperoni-12', name: '12"', price: 1299 },
    ],
  },
  {
    id: 'mock-afghan-special-pizza',
    name: 'Afghan Special Pizza (Lamb & Chilli)',
    slug: 'afghan-special-pizza',
    description: 'Spiced lamb with green chillies.',
    category: 'Pizza',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-asp-10', name: '10"', price: 1149 },
      { id: 'mock-asp-12', name: '12"', price: 1349 },
    ],
  },
  {
    id: 'mock-vegetarian-supreme',
    name: 'Vegetarian Supreme',
    slug: 'vegetarian-supreme',
    description: 'Mixed vegetables and cheese.',
    category: 'Pizza',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-veg-supreme-10', name: '10"', price: 999 },
      { id: 'mock-veg-supreme-12', name: '12"', price: 1199 },
    ],
  },
  {
    id: 'mock-chips',
    name: 'Chips',
    slug: 'chips',
    description: 'Classic salted fries.',
    category: 'Sides',
    popular: false,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-chips-standard', name: 'Standard', price: 299 },
    ],
  },
  {
    id: 'mock-cheesy-chips',
    name: 'Cheesy Chips',
    slug: 'cheesy-chips',
    description: 'Melted cheese over crispy fries.',
    category: 'Sides',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-cheesy-chips-standard', name: 'Standard', price: 449 },
    ],
  },
  {
    id: 'mock-spicy-wings',
    name: 'Spicy Wings (6pcs)',
    slug: 'spicy-wings',
    description: 'Fiery glazed wings.',
    category: 'Sides',
    popular: true,
    allergens: 'Gluten',
    variants: [
      { id: 'mock-spicy-wings-standard', name: 'Standard', price: 599 },
    ],
  },
  {
    id: 'mock-garlic-bread',
    name: 'Garlic Bread',
    slug: 'garlic-bread',
    description: 'Four slices of garlic bread.',
    category: 'Sides',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-garlic-bread-standard', name: 'Standard', price: 349 },
    ],
  },
  {
    id: 'mock-warm-cookies',
    name: 'Warm Cookies (4pcs)',
    slug: 'warm-cookies',
    description: 'Gooey chocolate chip cookies.',
    category: 'Desserts',
    popular: false,
    allergens: 'Gluten, Dairy, Eggs',
    variants: [
      { id: 'mock-warm-cookies-standard', name: 'Standard', price: 449 },
    ],
  },
  {
    id: 'mock-chocolate-fudge-cake',
    name: 'Chocolate Fudge Cake',
    slug: 'chocolate-fudge-cake',
    description: 'Rich chocolate slice.',
    category: 'Desserts',
    popular: false,
    allergens: 'Gluten, Dairy, Eggs',
    variants: [
      { id: 'mock-cfc-standard', name: 'Standard', price: 499 },
    ],
  },
  {
    id: 'mock-gulab-jamun',
    name: 'Gulab Jamun',
    slug: 'gulab-jamun',
    description: 'Three pieces in syrup.',
    category: 'Desserts',
    popular: false,
    allergens: 'Dairy, Gluten',
    variants: [
      { id: 'mock-gj-standard', name: 'Standard', price: 399 },
    ],
  },
  {
    id: 'mock-baklava',
    name: 'Baklava (2pcs)',
    slug: 'baklava',
    description: 'Rich pastry with honey & nuts.',
    category: 'Desserts',
    popular: false,
    allergens: 'Gluten, Nuts',
    variants: [
      { id: 'mock-baklava-standard', name: 'Standard', price: 349 },
    ],
  },
  {
    id: 'mock-coca-cola',
    name: 'Coca-Cola',
    slug: 'coca-cola',
    description: '330ml can.',
    category: 'Drinks',
    popular: false,
    allergens: 'None',
    variants: [
      { id: 'mock-coke-standard', name: 'Standard', price: 149 },
    ],
  },
  {
    id: 'mock-sprite',
    name: 'Sprite',
    slug: 'sprite',
    description: '330ml can.',
    category: 'Drinks',
    popular: false,
    allergens: 'None',
    variants: [
      { id: 'mock-sprite-standard', name: 'Standard', price: 149 },
    ],
  },
  {
    id: 'mock-fanta-orange',
    name: 'Fanta Orange',
    slug: 'fanta-orange',
    description: '330ml can.',
    category: 'Drinks',
    popular: false,
    allergens: 'None',
    variants: [
      { id: 'mock-fanta-standard', name: 'Standard', price: 149 },
    ],
  },
  {
    id: 'mock-water',
    name: 'Water',
    slug: 'water',
    description: '500ml bottle.',
    category: 'Drinks',
    popular: false,
    allergens: 'None',
    variants: [
      { id: 'mock-water-standard', name: 'Standard', price: 100 },
    ],
  },
  {
    id: 'mock-deal-1',
    name: "Nomad's Deal 1",
    slug: 'nomads-deal-1',
    description: 'Lamb Doner, Chicken Doner, Chips, Kabuli Pilau Rice, Salad, Sauces & 2 Drinks.',
    category: 'Deals',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-deal-1-standard', name: 'Standard', price: 1799 },
    ],
  },
  {
    id: 'mock-deal-2',
    name: "Nomad's Deal 2",
    slug: 'nomads-deal-2',
    description: 'Any Medium Pizza + Chicken Strips or Wings + Chips + Drink.',
    category: 'Deals',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-deal-2-standard', name: 'Standard', price: 1999 },
    ],
  },
  {
    id: 'mock-deal-3',
    name: "Nomad's Deal 3",
    slug: 'nomads-deal-3',
    description: 'Two Medium Pizzas + Warm Cookies + Chips/Fries + 2 Drinks.',
    category: 'Deals',
    popular: false,
    allergens: 'Gluten, Dairy, Eggs',
    variants: [
      { id: 'mock-deal-3-standard', name: 'Standard', price: 3199 },
    ],
  },
  {
    id: 'mock-deal-4',
    name: "Nomad's Deal 4",
    slug: 'nomads-deal-4',
    description: 'Any Two Large Pizzas.',
    category: 'Deals',
    popular: false,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-deal-4-standard', name: 'Standard', price: 2599 },
    ],
  },
  {
    id: 'mock-afghan-family-platter',
    name: 'Afghan Family Platter',
    slug: 'afghan-family-platter',
    description: 'Mix Grill (Lamb, Chicken, Kebab) + Pilau + Bread + Salad + Sauces.',
    category: 'Deals',
    popular: true,
    allergens: 'Gluten, Dairy',
    variants: [
      { id: 'mock-family-platter-standard', name: 'Standard', price: 3999 },
    ],
  },
];

